apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.2.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v2
  name: portieris-operator.vX.Y.Z
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Portieris is the Schema for the portieris API
      displayName: Portieris
      kind: Portieris
      name: portieris.apis.portieris.io
      version: v1alpha1
  description: Portieris Operator
  displayName: Portieris Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - image integrity
  links:
  - name: Portieris Operator
    url: https://portieris-operator.domain
  maturity: alpha
  provider:
    name: IBM
    url: https://github.ibm.com/rurikudo/portieris
  version: 0.0.0
