apiVersion: apis.portieris.io/v1alpha1
kind: Portieris
metadata:
  name: portieris
  # finalizers:
  #   - cleanup.finalizers.portieris.io
spec:
  name: portieris
  enableCosignVerify: true
  cosignVerifierImage: localhost:5000/cosign-verifier:0.0.12
  allowAdmissionSkip: false
  IBMContainerService: false
  skipSecretCreation: false
  secretName: portieris-certs
  useCertManager: false
  selector:
    app: portieris
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - portieris
          topologyKey: kubernetes.io/hostname
        weight: 50
      - podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - portieris
          topologyKey: failure-domain.beta.kubernetes.io/zone
        weight: 50
  allowedRepositories:
  - '*'
  image:
    host: localhost:5000
    image: portieris
    pullPolicy: Always
    pullSecret: []
    tag: cv7
  nodeSelector: {}
  replicaCount: 1
  resources:
    limits:
      cpu: 400m
      memory: 600Mi
    requests:
      cpu: 40m
      memory: 60Mi
  securityContext:
    runAsUser: 1000060001
  service:
    metricsTargetPort: 8080
    metricsPort: 8080
    port: 443
    targetPort: 8000
    type: ClusterIP
  tolerations: []
  webHooks:
    failurePolicy: Fail
  securityContextConstraints: false
  
  
