apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: portieris-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: Portieris Operator
  image: quay.io/gajananan/portieris-operator-index:0.10.7
  publisher: IBM
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 45m